### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Anujmoglix** [lklima/motion-pizza#1]
Tried that repo but it is not working.

1. Asset file is not updated. 
2. After commenting unavailable link getting 

> Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s%s, undefined,  You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Main`., 
    in Main (created by App)
    in ThemeProvider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

**Comment by lklima** [comment]
Are you running in android or ios ? I tried on both and worked .
You also must have latest expo-cli version.

**Comment by Anujmoglix** [comment]
checked on android. I am not sure about the latest expo-cli version, surely update.

**Comment by lklima** [comment]
I updated some android config, update expo cli and try again
